language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script: phpunit --coverage-text

notifications:
  email:
    - pierre@elbcoast.net