language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - TEST_COMMAND="composer test"
  matrix:
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.4.*

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - $TEST_COMMAND

notifications:
  email:
    - pierre@elbcoast.net
