language: php

sudo: false

php:
  - 5.6
  - 7.1
  - 7.2
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - TEST_COMMAND="composer test"
  matrix:
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.3.*
    - SYMFONY_VERSION=3.4.*

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - $TEST_COMMAND

notifications:
  email:
    - pierre@elbcoast.net
