language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - TEST_COMMAND="composer test"
  matrix:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=dev-master

matrix:
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true SYMFONY_VERSION=2.3.* TEST_COMMAND="composer test-ci"
  exclude:
    - php: 5.4
      env: SYMFONY_VERSION=dev-master
    - php: 5.4
      env: SYMFONY_VERSION=3.0.*

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - $TEST_COMMAND

notifications:
  email:
    - pierre@elbcoast.net
